[project]
name = "corerl"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["eval", "agents", "train", "dynamics", "environments", "utils", "SAC_Code"]